
services:
  db:
    image: postgres:16-alpine           # Imagen liviana de Postgres 16
    container_name: fs_db               # Nombre del contenedor
    environment:                        # Variables para inicializar la DB
      POSTGRES_DB: ${POSTGRES_DB}               # Uso de variables de entorno de .env
      POSTGRES_USER: ${POSTGRES_USER}           # Uso de variables de entorno de .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   # Uso de variables de entorno de .env
    ports:
      - "55432:5432"                    # Puerto host : Puerto predeterminado postgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data # Datos persistentes (no se pierden)

    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
          interval: 5s
          timeout: 3s
          retries: 20
    networks:
      - mi_red

  serv-backend:
    build: ./backend                    # Construye con Dockerfile de backend/
    container_name: fs_backend          # Nombre del contenedor
    env_file: .env                      # Carga variables de entorno
    user: "${UID:-1000}:${GID:-1000}"   # En linux/WSL evita archivos creados como root
    command: /bin/sh -lc "./entrypoint.sh"
    volumes:
      - ./backend:/app                  # Hot-reload: tu código ↔ contenedor
      - backend_static:/app/staticfiles # Estaticos recopilados
      - backend_media:/app/media        # Archivos subidos
    ports:
      - "8000:8000"                     # Puerto host : puerto predeterminado Django
    networks:
      - mi_red  # Conectar a la misma red para que se puedan comunicar
    depends_on:
      db:
        condition: service_healthy      # Espera a que la DB este OK


  serv-frontend:
    build:
      context: ./frontend
    # image: node:18
    container_name: frontend
    ports:
      - "5173:5173"   #Puerto de React con vite
    depends_on:
      - serv-backend
    working_dir: /app
    volumes:
      - ./frontend:/app  # Montar el código fuente local para hot reload en el frontend
      # - ./frontend/ssl:/app/ssl # Usar ssl
      - node_modules_frontend:/app/node_modules  # Evitar que los node_modules del host interfieran con los del contenedor
    environment:
      # - CHOKIDAR_USEPOLLING=true    #Activa el hot reload de React
      - HOST=0.0.0.0  # Necesario para que Vite escuche fuera del contenedor
    networks:
      - mi_red

volumes:
  pgdata:
  backend_static:
  backend_media:
  node_modules_frontend:

networks:
  mi_red:
    driver: bridge

