
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
          interval: 5s
          timeout: 3s
          retries: 20
    networks:
      - mi-red

  backend:
    build: 
      context: . # Construye con Dockerfile de backend/
      dockerfile: ./backend/Dockerfile
    env_file: .env # Carga variables de entorno
    volumes:
      - ./backend:/app # Hot-reload: tu código ↔ contenedor
      - backend-static:/app/staticfiles # Estaticos recopilados
      - backend-media:/app/media # Archivos subidos
    ports:
      - "8000:8000" # Puerto host : puerto predeterminado Django
    networks:
      - mi-red # Conectar a la misma red para que se puedan comunicar
    depends_on:
      db:
        condition: service_healthy # Espera a que la DB este OK


  frontend:
    build: 
      context: . # Construye con Dockerfile de backend/
      dockerfile: ./frontend/Dockerfile
    env_file: .env
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./frontend:/app # Montar el código fuente local para hot reload en el frontend
      # - ./frontend/ssl:/app/ssl # Usar ssl
      - node_modules:/app/node_modules  # Evitar que los node_modules del host interfieran con los del contenedor
    ports:
      - "5173:5173" #Puerto de React con vite
    environment:
      - HOST=0.0.0.0 # Necesario para que Vite escuche fuera del contenedor
      # - CHOKIDAR_USEPOLLING=true #Activa el hot reload de React
    networks:
      - mi-red

volumes:
  postgres-data:
  backend-static:
  backend-media:
  node_modules:

networks:
  mi-red:
    driver: bridge

