format = """$username $character$directory $git_branch$git_state $cmd_duration $line_break$python$character"""

[username]
style_user = "green bold"
format = "[$user]($style)"
show_always = true

[directory]
style = "blue bold"
format = "[$path]($style)"
truncation_length = 0

[character]
success_symbol = "[→](green)"
error_symbol = "[→](red)"
vicmd_symbol = "[←](green)"